apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: prometheus-node-exporter
spec:
  type: LoadBalancer           # Changed from NodePort to LoadBalancer
  selector:
    app: node-exporter
  ports:
    - name: node-exporter
      protocol: TCP
      port: 9100               # Service port
      targetPort: 9100         # Container port
