apiVersion: v1
kind: Service
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  type: LoadBalancer           # Changed from NodePort to LoadBalancer
  ports:
    - port: 3000               # Service port
      targetPort: 3000         # Container port
  selector:
    app: zomato
